version: '3.4'

services:
  uzbekcuisines.web.api:
    image: ${DOCKER_REGISTRY-}uzbekcuisineswebapi
    build:
      context: .
      dockerfile: src/UzbekCuisines.Web.Api/Dockerfile

  uzbekcuisines.db:
    image: postgres:latest
    container_name: Database
    environment:
      - POSTGRES_DB=uzbekcuisines-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - D:/Projects/Mine/uzbek-cuisines/src:/var/lib/postgresql/data
    ports:
      - 5432:5432 
  uzbekcuisines.mq:
    image: rabbitmq:3-management
    container_name: uzbekcuisines-mq
    hostname: uzbekcuisines-mq
    volumes:
        - D:/Projects/Mine/uzbek-cuisines/queue/data/:/var/lib/rabbitmq
        - D:/Projects/Mine/uzbek-cuisines/queue/log/:/var/lab/rabbitmq
    ports:
        - 5672:5672
        - 15672:15672 
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
